create table house_information
(
    address_id           serial not null
        constraint house_information_pkey
            primary key,
    address              varchar(256),
    region               varchar(256),
    city                 varchar(256),
    street               varchar(256),
    status               boolean,
    year_of_occupancy    integer,
    number_of_floors     integer,
    last_update          varchar(256),
    type_of_construction varchar(256),
    house_type           varchar(256),
    wreck_status         boolean,
    cadastral_number     varchar(256),
    type_of_cellings     varchar(256),
    walls_material       varchar(256)
);

alter table house_information
    owner to aydar;

INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (1, 'Санкт-Петербург, ул. Репищева, д. 21, к. 1', 'Санкт-Петербург', 'Санкт-Петербург', 'ул. Репищева', true, 1993, 16, '28.10.2021', '137', 'Многоквартирный дом', false, null, 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (2, 'Коми , г. Печора, пр-кт. Печорский, д. 116', 'Коми , ', 'г. Печора', 'пр-кт. Печорский', true, 1985, 5, '11.11.2021', 'кирпичный', 'Многоквартирный дом', false, '11:12:1701004:1121', 'Железобетонные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (3, 'Санкт-Петербург, линия. 6-я В.О., д. 47', 'Санкт-Петербург', 'Санкт-Петербург', 'линия. 6-я В.О.', true, 1916, 1, '28.10.2021', 'Кирпичный', 'Многоквартирный дом', false, '78:06:0002025:2020', 'Смешанные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (4, 'Москва, пер. Яковоапостольский, д. 9, к. 2', 'Москва', 'Москва', 'пер. Яковоапостольский', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (5, 'Татарстан , с. Осиново, ул. Кооперативная, д. 16А', 'Татарстан , ', 'с. Осиново', 'ул. Кооперативная', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (6, 'Коми , г. Печора, ул. Ленина, д. 29', 'Коми , ', 'г. Печора', 'ул. Ленина', true, 1986, 9, '11.11.2021', 'панельный', 'Многоквартирный дом', false, '11:12:1702003:4144', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (7, 'Московская , д. Доронино, . , д. 0', 'Московская , ', 'д. Доронино', '. ', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (8, 'Москва, ул. Чичерина, д. 2018-09-02 00:00:00', 'Москва', 'Москва', 'ул. Чичерина', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (9, 'Москва, . , д. 0, к. 906', 'Москва', 'Москва', '. ', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (10, 'Калининградская , г. Калининград, ул. Согласия, д. 33', 'Калининградская , ', 'г. Калининград', 'ул. Согласия', true, 2008, 10, '28.10.2021', 'ФК-1750-8', 'Многоквартирный дом', false, null, 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (11, 'Белгородская , пгт. Прохоровка, ул. Совхозная, д. 9', 'Белгородская , ', 'пгт. Прохоровка', 'ул. Совхозная', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (12, 'Тверская , г. Тверь, ул. Склизкова, д. 70, к. 4', 'Тверская , ', 'г. Тверь', 'ул. Склизкова', true, 1979, 9, '28.10.2021', '111-121-К ЭБ-8-9', 'Многоквартирный дом', false, '69:40:0200041:11', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (13, 'Москва, проезд. Марьиной Рощи 5-й, д. 14в', 'Москва', 'Москва', 'проезд. Марьиной Рощи 5-й', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (14, 'Калмыкия , п. Большой Царын, ул. С.Убушиева, д. 9', 'Калмыкия , ', 'п. Большой Царын', 'ул. С.Убушиева', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (15, 'Санкт-Петербург, ул. Первого Мая, д. 10, к. 6', 'Санкт-Петербург', 'Санкт-Петербург', 'ул. Первого Мая', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (16, 'Воронежская , х. Михайловка, ул. Песчаная, д. 39', 'Воронежская , ', 'х. Михайловка', 'ул. Песчаная', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (17, 'Московская , д. Крюково, . , д. 80/1', 'Московская , ', 'д. Крюково', '. ', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (18, 'Санкт-Петербург, пр-кт. Стачек, д. 101, к. 1', 'Санкт-Петербург', 'Санкт-Петербург', 'пр-кт. Стачек', true, 1976, 1, '28.10.2021', 'ЛГ-600', 'Многоквартирный дом', false, '78:15:0008301:3012', 'Железобетонные', 'Блочные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (19, 'Москва, ул. Академика Янгеля, д. 1, к. 1', 'Москва', 'Москва', 'ул. Академика Янгеля', true, 2011, 18, '12.11.2021', 'индивидуальный проект', 'Многоквартирный дом', false, null, 'Железобетонные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (20, 'Калининградская , г. Калининград, ул. Лукашова, д. 11а', 'Калининградская , ', 'г. Калининград', 'ул. Лукашова', true, 2011, 6, '28.10.2021', 'Многоквартирный дом, кирпичный', 'Многоквартирный дом', false, '39:15:120308:37 (Жиленкова,8б,10а; Лукашова, 11а,11б,11)', 'Железобетонные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (21, 'Воронежская , г. Нововоронеж, ул. Космонавтов, д. 35', 'Воронежская , ', 'г. Нововоронеж', 'ул. Космонавтов', true, 1981, 5, '28.10.2021', '111-125-8', 'Многоквартирный дом', false, '36:33:0002403:66', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (22, 'Санкт-Петербург, ул. Стойкости, д. 7', 'Санкт-Петербург', 'Санкт-Петербург', 'ул. Стойкости', true, 1969, 9, '28.10.2021', '1ЛГ-600А', 'Многоквартирный дом', false, null, 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (23, 'Москва, ул. Академика Пилюгина, д. 26, к. 3', 'Москва', 'Москва', 'ул. Академика Пилюгина', true, 1986, 22, '12.11.2021', 'КОПЭ', 'Многоквартирный дом', false, '77:06:0003010:1014', 'Площадь наружной части фундамента, кв. м 1127,5', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (24, 'Московская , г. Королев, проезд. Циолковского, д. 20/22', 'Московская , ', 'г. Королев', 'проезд. Циолковского', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (25, 'Краснодарский , с. Эстосадок, ул. Подгорная, д. 75', 'Краснодарский , ', 'с. Эстосадок', 'ул. Подгорная', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (26, 'Калужская , д. Любицы, . , д. 13', 'Калужская , ', 'д. Любицы', '. ', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (27, 'Краснодарский , г. Новороссийск, ул. Карла Маркса, д. 1', 'Краснодарский , ', 'г. Новороссийск', 'ул. Карла Маркса', true, 1968, 5, '11.11.2021', 'Типовой', 'Многоквартирный дом', false, '23:47:0301008:66', 'Железобетонные', 'Блочные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (28, 'Краснодарский , г. Анапа, ул. Ленина, д. 134', 'Краснодарский , ', 'г. Анапа', 'ул. Ленина', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (29, 'Ростовская , х. Петровка, ул. Социалистическая, д. 18', 'Ростовская , ', 'х. Петровка', 'ул. Социалистическая', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (30, 'Коми , г. Ухта, пр-кт. Космонавтов, д. 26', 'Коми , ', 'г. Ухта', 'пр-кт. Космонавтов', true, 1982, null, '11.11.2021', null, 'Не заполнено', false, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (31, 'Чувашская Республика - , г. Чебоксары, ул. Ленинского Комсомола, д. 34/8, к. 1', 'Чувашская Республика - , ', 'г. Чебоксары', 'ул. Ленинского Комсомола', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (32, 'Краснодарский , г. Краснодар, снт. Любитель, д. 286', 'Краснодарский , ', 'г. Краснодар', 'снт. Любитель', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (33, 'Москва, проезд. Булатниковский, д. 14, к. 1', 'Москва', 'Москва', 'проезд. Булатниковский', true, 1974, 12, '12.11.2021', 'П-47', 'Многоквартирный дом', false, '77:05:0009003:1036', 'Площадь стен и перегородок в помещениях общего пользования, кв. м 3600', 'Железобетон');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (34, 'Владимирская , п. Мелехово, ул. Первомайская, д. 31', 'Владимирская , ', 'п. Мелехово', 'ул. Первомайская', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (35, 'Санкт-Петербург, ул. Партизана Германа, д. 41', 'Санкт-Петербург', 'Санкт-Петербург', 'ул. Партизана Германа', true, 1972, 9, '28.10.2021', 'ЛГ 600', 'Многоквартирный дом', false, '78:40:0008459:3010', 'Железобетонные', 'Смешанные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (36, 'Ленинградская , г. Тихвин, мкр. 6, д. 10', 'Ленинградская , ', 'г. Тихвин', 'мкр. 6', true, 1978, 9, '28.10.2021', '1ЛГ600А', 'Многоквартирный дом', false, '47:13:1202025:45', null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (37, 'Санкт-Петербург, пр-кт. Северный, д. 6, к. 1', 'Санкт-Петербург', 'Санкт-Петербург', 'пр-кт. Северный', true, 1978, 12, '28.10.2021', '1-ЛГ-600 А', 'Многоквартирный дом', false, '78:36:0553301:5770', null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (38, 'Ленинградская , д. Кудрово, ул. Столичная, д. 11, к. 2', 'Ленинградская , ', 'д. Кудрово', 'ул. Столичная', true, 2018, 21, '28.10.2021', 'Индивидуальный', 'Многоквартирный дом', false, '47:07:1044001:620', null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (39, 'Воронежская , д. Богданово, ул. Лесная, д. 2', 'Воронежская , ', 'д. Богданово', 'ул. Лесная', true, 1993, 3, '28.10.2021', null, 'Многоквартирный дом', false, '36:25:1600002:97', null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (40, 'Краснодарский , ст-ца. Елизаветинская, ул. Широкая, д. 83', 'Краснодарский , ', 'ст-ца. Елизаветинская', 'ул. Широкая', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (41, 'Краснодарский , г. Кореновск, ул. Краснодарская, д. 12', 'Краснодарский , ', 'г. Кореновск', 'ул. Краснодарская', true, 2011, 9, '28.10.2021', null, 'Не заполнено', false, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (42, 'Краснодарский , г. Краснодар, ул. им Димитрова, д. 144', 'Краснодарский , ', 'г. Краснодар', 'ул. им Димитрова', true, 1998, 12, '11.11.2021', null, 'Многоквартирный дом', false, '23:43:0309001:9', null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (43, 'Московская , г. Ногинск, ул. 3 Интернационала, д. 38А', 'Московская , ', 'г. Ногинск', 'ул. 3 Интернационала', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (44, 'Пермский , п. Дивья, ул. Рабочая, д. 68', 'Пермский , ', 'п. Дивья', 'ул. Рабочая', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (45, 'Саратовская , г. Саратов, ул. Моторная, д. 10', 'Саратовская , ', 'г. Саратов', 'ул. Моторная', true, 1978, 9, '28.10.2021', 'панельный', 'Многоквартирный дом', false, '64:48:040237:39', null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (46, 'Краснодарский , г. Анапа, ул. Стахановская, д. 9', 'Краснодарский , ', 'г. Анапа', 'ул. Стахановская', true, 1985, 5, '28.10.2021', 'типовой', 'Многоквартирный дом', false, '23:37:0109001:142', null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (47, 'Калининградская , г. Калининград, ул. Батальная, д. 15', 'Калининградская , ', 'г. Калининград', 'ул. Батальная', true, 1957, 2, '28.10.2021', 'нет', 'Многоквартирный дом', false, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (48, 'Москва, ул. Яблочкова, д. 4', 'Москва', 'Москва', 'ул. Яблочкова', true, 1967, 9, '12.11.2021', 'П-57', 'Многоквартирный дом', false, null, 'Протяженность трубопроводов горячей воды, м 1314', 'Блочные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (49, 'Краснодарский , п. Южный, ул. Линейная, д. 5', 'Краснодарский , ', 'п. Южный', 'ул. Линейная', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (50, 'Татарстан , г. Набережные Челны, ул. Шамиля Усманова, д. 108', 'Татарстан , ', 'г. Набережные Челны', 'ул. Шамиля Усманова', true, 1979, 9, '28.10.2021', null, 'Многоквартирный дом', false, '16:52:060203:70', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (51, 'Саратовская , г. Вольск, пер. Горького 1-й, д. 18', 'Саратовская , ', 'г. Вольск', 'пер. Горького 1-й', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (52, 'Ростовская , х. Петровка, ул. Социалистическая, д. 18', 'Ростовская , ', 'х. Петровка', 'ул. Социалистическая', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (53, 'Калужская , д. Любицы, . , д. 13', 'Калужская , ', 'д. Любицы', '. ', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (54, 'Владимирская , п. Мелехово, ул. Первомайская, д. 31', 'Владимирская , ', 'п. Мелехово', 'ул. Первомайская', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (55, 'Свердловская , г. Каменск-Уральский, ул. Добролюбова, д. 16', 'Свердловская , ', 'г. Каменск-Уральский', 'ул. Добролюбова', true, 1965, 4, '28.10.2021', '1-335-А', 'Многоквартирный дом', false, '66:45:0100136:0072', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (56, 'Воронежская , г. Воронеж, ул. Просторная, д. 34', 'Воронежская , ', 'г. Воронеж', 'ул. Просторная', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (57, 'Карачаево-Черкесская , г. Черкесск, ул. Фурманова, д. 153', 'Карачаево-Черкесская , ', 'г. Черкесск', 'ул. Фурманова', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (58, 'Москва, ул. Нагорная, д. 10', 'Москва', 'Москва', 'ул. Нагорная', true, 2009, 17, '12.11.2021', 'индивидуальный проект', 'Многоквартирный дом', false, null, 'Площадь стен и перегородок в помещениях общего пользования, кв. м 742,7', 'Монолитные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (59, 'Краснодарский , х. Шевченко, ул. Октябрьская, д. 41', 'Краснодарский , ', 'х. Шевченко', 'ул. Октябрьская', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (60, 'Калужская , г. Калуга, ул. Генерала Попова, д. 18, к. 3', 'Калужская , ', 'г. Калуга', 'ул. Генерала Попова', true, 1994, 9, '13.11.2021', 'кирпичный', 'Многоквартирный дом', false, null, 'Иные', 'Иные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (61, 'Новгородская , г. Великий Новгород, пр-кт. Александра Корсунова, д. 47', 'Новгородская , ', 'г. Великий Новгород', 'пр-кт. Александра Корсунова', true, 1988, 10, '28.10.2021', 'с-90', 'Многоквартирный дом', false, '53:23:8101202:9', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (62, 'Омская , г. Омск, ул. Молодежная 3-я, д. 75', 'Омская , ', 'г. Омск', 'ул. Молодежная 3-я', true, 1984, 9, '28.10.2021', '1-464', 'Многоквартирный дом', false, 'Отсутствует', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (63, 'Ростовская , г. Новочеркасск, ул. Петрова, д. 27 Г', 'Ростовская , ', 'г. Новочеркасск', 'ул. Петрова', true, 1970, 5, '10.11.2021', null, 'Многоквартирный дом', false, null, 'Железобетонные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (64, 'Краснодарский , ст-ца. Елизаветинская, ул. Широкая, д. 83', 'Краснодарский , ', 'ст-ца. Елизаветинская', 'ул. Широкая', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (65, 'Ульяновская , г. Ульяновск, ул. Гафурова, д. 43', 'Ульяновская , ', 'г. Ульяновск', 'ул. Гафурова', true, 1968, 5, '12.11.2021', 'Строение', 'Многоквартирный дом', false, 'не присвоен', 'Железобетонные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (66, 'Владимирская , п. Мелехово, ул. Первомайская, д. 31', 'Владимирская , ', 'п. Мелехово', 'ул. Первомайская', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (67, 'Кировская , г. Вятские Поляны, ул. Первомайская, д. 84', 'Кировская , ', 'г. Вятские Поляны', 'ул. Первомайская', true, 1984, 5, '28.10.2021', 'информация в тех.паспорте отсутствует', 'Многоквартирный дом', false, '43:41:000040:28', 'Железобетонные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (68, 'Московская , мкр. Гостица, . , д. 475', 'Московская , ', 'мкр. Гостица', '. ', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (69, 'Вологодская , с/т. Березка, . , д. уч.119', 'Вологодская , ', 'с/т. Березка', '. ', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (70, 'Челябинская , г. Сатка, ул. Солнечная, д. 15', 'Челябинская , ', 'г. Сатка', 'ул. Солнечная', true, 1969, 5, '28.10.2021', 'Гражданский', 'Многоквартирный дом', false, '74:18:0804155:17', 'Железобетонные', 'Смешанные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (71, 'Смоленская , г. Смоленск, ул. 25 Сентября, д. 54', 'Смоленская , ', 'г. Смоленск', 'ул. 25 Сентября', true, 1973, 9, '10.11.2021', null, 'Многоквартирный дом', false, '67:27:0030814:3', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (72, 'Калининградская , г. Калининград, ул. Куйбышева, д. 109', 'Калининградская , ', 'г. Калининград', 'ул. Куйбышева', true, null, null, '28.10.2021', null, 'Не заполнено', false, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (73, 'Омская , г. Омск, ул. Молодежная 3-я, д. 75', 'Омская , ', 'г. Омск', 'ул. Молодежная 3-я', true, 1984, 9, '28.10.2021', '1-464', 'Многоквартирный дом', false, 'Отсутствует', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (74, 'Москва, ул. Нагорная, д. 10', 'Москва', 'Москва', 'ул. Нагорная', true, 2009, 17, '12.11.2021', 'индивидуальный проект', 'Многоквартирный дом', false, null, 'Площадь стен и перегородок в помещениях общего пользования, кв. м 742,7', 'Монолитные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (75, 'Московская , рп. Софрино, ул. Заводская, д. 5', 'Московская , ', 'рп. Софрино', 'ул. Заводская', true, 1986, 5, '28.10.2021', 'панельный', 'Многоквартирный дом', false, '50:13:0020208', 'Железобетонные', 'Блочные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (76, 'Курская , г. Курск, ул. Белинского, д. 1 А', 'Курская , ', 'г. Курск', 'ул. Белинского', true, 1937, 4, '28.10.2021', 'ТП-111-2022/2', 'Многоквартирный дом', false, '46/11-1-18789', 'Смешанные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (77, 'Краснодарский , с/т. Восход, . , д. 223', 'Краснодарский , ', 'с/т. Восход', '. ', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (78, 'Омская , г. Омск, ул. Г.В.Комнатова, д. 7', 'Омская , ', 'г. Омск', 'ул. Г.В.Комнатова', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (79, 'Московская асть , . Некрпасовский, . Заводская, д. 31', 'Московская асть , ', '. Некрпасовский', '. Заводская', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (80, 'Московская , п. Софрино, ул. Заводская, д. 2', 'Московская , ', 'п. Софрино', 'ул. Заводская', true, 2012, 5, '28.10.2021', 'кирпичный', 'Многоквартирный дом', false, '50:13:0020208', 'Железобетонные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (81, 'Челябинская , г. Челябинск, ул. Ковалевской, д. 3', 'Челябинская , ', 'г. Челябинск', 'ул. Ковалевской', true, 1955, 2, '28.10.2021', null, 'Многоквартирный дом', false, null, 'Смешанные', 'Иные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (82, 'Оренбургская , д. Второе Юмагузино, ул. Иментамакская, д. 61', 'Оренбургская , ', 'д. Второе Юмагузино', 'ул. Иментамакская', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (83, 'Челябинская , с. Еткуль, пер. 8-й, д. 5', 'Челябинская , ', 'с. Еткуль', 'пер. 8-й', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (84, 'Саратовская , с. Синодское, ул. Клочкова, д. 90/2', 'Саратовская , ', 'с. Синодское', 'ул. Клочкова', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (85, 'Челябинская , г. Кыштым, ул. Карла Либкнехта, д. 230', 'Челябинская , ', 'г. Кыштым', 'ул. Карла Либкнехта', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (86, 'Владимирская , пгт. Мелехово, ул. Первомайская, д. 31', 'Владимирская , ', 'пгт. Мелехово', 'ул. Первомайская', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (87, 'Омская , г. Омск, ул. Молодежная 3-я, д. 75', 'Омская , ', 'г. Омск', 'ул. Молодежная 3-я', true, 1984, 9, '28.10.2021', '1-464', 'Многоквартирный дом', false, 'Отсутствует', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (88, 'Курская , г. Курск, ул. Минина, д. 50', 'Курская , ', 'г. Курск', 'ул. Минина', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (89, 'Башкортостан , г. Салават, ул. Революционная, д. 3', 'Башкортостан , ', 'г. Салават', 'ул. Революционная', true, 1985, 5, '11.11.2021', '86', 'Многоквартирный дом', false, '02:59:070127:17', 'Железобетонные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (90, 'Москва, пр-кт. Волгоградский, д. 159, к. 1', 'Москва', 'Москва', 'пр-кт. Волгоградский', true, 1962, 5, '28.10.2021', 'I-515', 'Многоквартирный дом', false, 'нет', 'Площадь наружных стен, кв. м 0', 'Железобетон');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (91, 'Челябинская , г. Челябинск, ул. 40-летия Победы, д. 3', 'Челябинская , ', 'г. Челябинск', 'ул. 40-летия Победы', true, 2011, 20, '28.10.2021', 'Индивидуальный 06.16-09', 'Многоквартирный дом', false, 'нет', 'Железобетонные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (92, 'Краснодарский , с/т. Восход, . , д. 223', 'Краснодарский , ', 'с/т. Восход', '. ', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (93, 'Свердловская , г. Каменск-Уральский, пр-кт. Победы, д. 48', 'Свердловская , ', 'г. Каменск-Уральский', 'пр-кт. Победы', true, 1969, 5, '28.10.2021', '1-335-А-2', 'Многоквартирный дом', false, '66:45:0100086:58', 'Железобетонные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (104, 'Москва, пер. Хилков, д. 5', 'Москва', 'Москва', 'пер. Хилков', true, null, null, '12.11.2021', null, 'Способ формирования фонда капитального ремонта: Счет регионального оператора', false, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (105, 'Омская , г. Омск, ул. Омская, д. 119', 'Омская , ', 'г. Омск', 'ул. Омская', true, 1987, 5, '28.10.2021', '1-335ом', 'Многоквартирный дом', false, 'нет', 'Смешанные', 'Панельные');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (106, 'Челябинская , г. Челябинск, пер. Мамина, д. 3', 'Челябинская , ', 'г. Челябинск', 'пер. Мамина', true, 1983, null, '28.10.2021', null, 'Многоквартирный дом', false, '74:36:0204001:40', null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (107, 'Саратовская , с. Синодское, ул. Клочкова, д. 90', 'Саратовская , ', 'с. Синодское', 'ул. Клочкова', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (108, 'Санкт-Петербург, наб. Реки Фонтанки, д. 50', 'Санкт-Петербург', 'Санкт-Петербург', 'наб. Реки Фонтанки', true, 1916, 5, '28.10.2021', 'Дореволюционная постройка', 'Многоквартирный дом', false, null, 'Железобетонные', 'Кирпич');
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (109, 'Владимирская , г. Ковров, ул. Сергея Лазо, д. 2021-01-06 00:00:00', 'Владимирская , ', 'г. Ковров', 'ул. Сергея Лазо', false, null, null, null, null, null, null, null, null, null);
INSERT INTO public.house_information (address_id, address, region, city, street, status, year_of_occupancy, number_of_floors, last_update, type_of_construction, house_type, wreck_status, cadastral_number, type_of_cellings, walls_material) VALUES (110, 'Владимирская , пос.. Мелехово, ул. Первомайская, д. 31', 'Владимирская , ', 'пос.. Мелехово', 'ул. Первомайская', false, null, null, null, null, null, null, null, null, null);